# Generated by Django 5.2 on 2025-05-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_person',
            field=models.IntegerField(default=1),
        ),
    ]
